services:
  php-apache:
    image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Puedes acceder a la aplicación a través de http://localhost:8080
    volumes:
      - ./portal_api:/var/www/html  # Monta el directorio local 'api' dentro del contenedor
    networks:
      - my-network   # Conectamos este contenedor a la red personalizada
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0  # Usa la imagen de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Configura la contraseña de root
      MYSQL_DATABASE: comunica_portalComunicacion  # Nombre de la base de datos a crear
      MYSQL_USER: USER
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"  # Exponer el puerto de la base de datos
    networks:
      - my-network  # Conectamos este contenedor a la red personalizada
    command: --bind-address=0.0.0.0

networks:
  my-network:
    driver: bridge
